class Answer
    def color
        "Use one of the following methods:\n`random` `aura` `date` `today` `hex` `name`"
    end

    def colorsCollection
        [
          ['Acid Green', 'B0BF1A'],
          %w(Aero 7CB9E8),
          ['Aero Blue', 'C9FFE5'],
          ['African Violet', 'B284BE'],
          ['Air Force Blue (RAF)', '5D8AA8'],
          ['Air Force Blue (USAF)', '00308F'],
          ['Air Superiority Blue', '72A0C1'],
          ['Alabama Crimson', 'AF002A'],
          ['Alice Blue', 'F0F8FF'],
          ['Alizarin Crimson', 'E32636'],
          ['Alloy Orange', 'C46210'],
          %w(Almond EFDECD),
          %w(Amaranth E52B50),
          ['Amaranth Deep Purple', 'AB274F'],
          ['Amaranth Pink', 'F19CBB'],
          ['Amaranth Purple', 'AB274F'],
          ['Amaranth Red', 'D3212D'],
          %w(Amazon 3B7A57),
          %w(Amber FFBF00),
          ['Amber (SAE/ECE)', 'FF7E00'],
          ['American Rose', 'FF033E'],
          %w(Amethyst 9966CC),
          ['Android Green', 'A4C639'],
          ['Anti-Flash White', 'F2F3F4'],
          ['Antique Brass', 'CD9575'],
          ['Antique Bronze', '665D1E'],
          ['Antique Fuchsia', '915C83'],
          ['Antique Ruby', '841B2D'],
          ['Antique White', 'FAEBD7'],
          ['Ao (English)', '008000'],
          ['Apple Green', '8DB600'],
          %w(Apricot FBCEB1),
          %w(Aqua 00FFFF),
          %w(Aquamarine 7FFFD4),
          ['Arctic Lime', 'D0FF14'],
          ['Army Green', '4B5320'],
          %w(Arsenic 3B444B),
          %w(Artichoke 8F9779),
          ['Arylide Yellow', 'E9D66B'],
          ['Ash Grey', 'B2BEB5'],
          %w(Asparagus 87A96B),
          ['Atomic Tangerine', 'FF9966'],
          %w(Auburn A52A2A),
          %w(Aureolin FDEE00),
          %w(AuroMetalSaurus 6E7F80),
          %w(Avocado 568203),
          %w(Azure 007FFF),
          ['Azure (Web Color)', 'F0FFFF'],
          ['Azure Mist', 'F0FFFF'],
          ['Azureish White', 'DBE9F4'],
          ['Baby Blue', '89CFF0'],
          ['Baby Blue Eyes', 'A1CAF1'],
          ['Baby Pink', 'F4C2C2'],
          ['Baby Powder', 'FEFEFA'],
          ['Baker-Miller Pink', 'FF91AF'],
          ['Ball Blue', '21ABCD'],
          ['Banana Mania', 'FAE7B5'],
          ['Banana Yellow', 'FFE135'],
          ['Bangladesh Green', '006A4E'],
          ['Barbie Pink', 'E0218A'],
          ['Barn Red', '7C0A02'],
          ['Battleship Grey', '848482'],
          %w(Bazaar 98777B),
          ['Beau Blue', 'BCD4E6'],
          %w(Beaver 9F8170),
          %w(Beige F5F5DC),
          ["B'dazzled Blue", '2E5894'],
          ["Big Dip O'ruby", '9C2542'],
          %w(Bisque FFE4C4),
          %w(Bistre 3D2B1F),
          ['Bistre Brown', '967117'],
          ['Bitter Lemon', 'CAE00D'],
          ['Bitter Lime', 'BFFF00'],
          %w(Bittersweet FE6F5E),
          ['Bittersweet Shimmer', 'BF4F51'],
          %w(Black 000000),
          ['Black Bean', '3D0C02'],
          ['Black Leather Jacket', '253529'],
          ['Black Olive', '3B3C36'],
          ['Blanched Almond', 'FFEBCD'],
          ['Blast-Off Bronze', 'A57164'],
          ['Bleu De France', '318CE7'],
          ['Blizzard Blue', 'ACE5EE'],
          %w(Blond FAF0BE),
          %w(Blue 0000FF),
          ['Blue (Crayola)', '1F75FE'],
          ['Blue (Munsell)', '0093AF'],
          ['Blue (NCS)', '0087BD'],
          ['Blue (Pantone)', '0018A8'],
          ['Blue (Pigment)', '333399'],
          ['Blue (RYB)', '0247FE'],
          ['Blue Bell', 'A2A2D0'],
          ['Blue-Gray', '6699CC'],
          ['Blue-Green', '0D98BA'],
          ['Blue Lagoon', '5E93A1'],
          ['Blue-Magenta Violet', '553592'],
          ['Blue Sapphire', '126180'],
          ['Blue-Violet', '8A2BE2'],
          ['Blue Yonder', '5072A7'],
          %w(Blueberry 4F86F7),
          %w(Bluebonnet 1C1CF0),
          %w(Blush DE5D83),
          %w(Bole 79443B),
          ['Bondi Blue', '0095B6'],
          %w(Bone E3DAC9),
          ['Boston University Red', 'CC0000'],
          ['Bottle Green', '006A4E'],
          %w(Boysenberry 873260),
          ['Brandeis Blue', '0070FF'],
          %w(Brass B5A642),
          ['Brick Red', 'CB4154'],
          ['Bright Cerulean', '1DACD6'],
          ['Bright Green', '66FF00'],
          ['Bright Lavender', 'BF94E4'],
          ['Bright Lilac', 'D891EF'],
          ['Bright Maroon', 'C32148'],
          ['Bright Navy Blue', '1974D2'],
          ['Bright Pink', 'FF007F'],
          ['Bright Turquoise', '08E8DE'],
          ['Bright Ube', 'D19FE8'],
          ['Brilliant Azure', '3399FF'],
          ['Brilliant Lavender', 'F4BBFF'],
          ['Brilliant Rose', 'FF55A3'],
          ['Brink Pink', 'FB607F'],
          ['British Racing Green', '004225'],
          %w(Bronze CD7F32),
          ['Bronze Yellow', '737000'],
          ['Brown (Traditional)', '964B00'],
          ['Brown (Web)', 'A52A2A'],
          ['Brown-Nose', '6B4423'],
          ['Brown Yellow', 'CC9966'],
          ['Brunswick Green', '1B4D3E'],
          ['Bubble Gum', 'FFC1CC'],
          %w(Bubbles E7FEFF),
          %w(Buff F0DC82),
          ['Bud Green', '7BB661'],
          ['Bulgarian Rose', '480607'],
          %w(Burgundy 800020),
          %w(Burlywood DEB887),
          ['Burnt Orange', 'CC5500'],
          ['Burnt Sienna', 'E97451'],
          ['Burnt Umber', '8A3324'],
          %w(Byzantine BD33A4),
          %w(Byzantium 702963),
          %w(Cadet 536872),
          ['Cadet Blue', '5F9EA0'],
          ['Cadet Grey', '91A3B0'],
          ['Cadmium Green', '006B3C'],
          ['Cadmium Orange', 'ED872D'],
          ['Cadmium Red', 'E30022'],
          ['Cadmium Yellow', 'FFF600'],
          ['Café Au Lait', 'A67B5B'],
          ['Café Noir', '4B3621'],
          ['Cal Poly Green', '1E4D2B'],
          ['Cambridge Blue', 'A3C1AD'],
          %w(Camel C19A6B),
          ['Cameo Pink', 'EFBBCC'],
          ['Camouflage Green', '78866B'],
          ['Canary Yellow', 'FFEF00'],
          ['Candy Apple Red', 'FF0800'],
          ['Candy Pink', 'E4717A'],
          %w(Capri 00BFFF),
          ['Caput Mortuum', '592720'],
          %w(Cardinal C41E3A),
          ['Caribbean Green', '00CC99'],
          %w(Carmine 960018),
          ['Carmine (M&P)', 'D70040'],
          ['Carmine Pink', 'EB4C42'],
          ['Carmine Red', 'FF0038'],
          ['Carnation Pink', 'FFA6C9'],
          %w(Carnelian B31B1B),
          ['Carolina Blue', '56A0D3'],
          ['Carrot Orange', 'ED9121'],
          ['Castleton Green', '00563F'],
          ['Catalina Blue', '062A78'],
          %w(Catawba 703642),
          ['Cedar Chest', 'C95A49'],
          %w(Ceil 92A1CF),
          %w(Celadon ACE1AF),
          ['Celadon Blue', '007BA7'],
          ['Celadon Green', '2F847C'],
          %w(Celeste B2FFFF),
          ['Celestial Blue', '4997D0'],
          %w(Cerise DE3163),
          ['Cerise Pink', 'EC3B83'],
          %w(Cerulean 007BA7),
          ['Cerulean Blue', '2A52BE'],
          ['Cerulean Frost', '6D9BC3'],
          ['CG Blue', '007AA5'],
          ['CG Red', 'E03C31'],
          %w(Chamoisee A0785A),
          %w(Champagne F7E7CE),
          %w(Charcoal 36454F),
          ['Charleston Green', '232B2B'],
          ['Charm Pink', 'E68FAC'],
          ['Chartreuse (Traditional)', 'DFFF00'],
          ['Chartreuse (Web)', '7FFF00'],
          %w(Cherry DE3163),
          ['Cherry Blossom Pink', 'FFB7C5'],
          %w(Chestnut 954535),
          ['China Pink', 'DE6FA1'],
          ['China Rose', 'A8516E'],
          ['Chinese Red', 'AA381E'],
          ['Chinese Violet', '856088'],
          ['Chocolate (Traditional)', '7B3F00'],
          ['Chocolate (Web)', 'D2691E'],
          ['Chrome Yellow', 'FFA700'],
          %w(Cinereous 98817B),
          %w(Cinnabar E34234),
          %w(Cinnamon D2691E),
          %w(Citrine E4D00A),
          %w(Citron 9FA91F),
          %w(Claret 7F1734),
          ['Classic Rose', 'FBCCE7'],
          ['Cobalt Blue', '0047AB'],
          ['Cocoa Brown', 'D2691E'],
          %w(Coconut 965A3E),
          %w(Coffee 6F4E37),
          ['Columbia Blue', 'C4D8E2'],
          ['Congo Pink', 'F88379'],
          ['Cool Black', '002E63'],
          ['Cool Grey', '8C92AC'],
          %w(Copper B87333),
          ['Copper (Crayola)', 'DA8A67'],
          ['Copper Penny', 'AD6F69'],
          ['Copper Red', 'CB6D51'],
          ['Copper Rose', '996666'],
          %w(Coquelicot FF3800),
          %w(Coral FF7F50),
          ['Coral Pink', 'F88379'],
          ['Coral Red', 'FF4040'],
          %w(Cordovan 893F45),
          %w(Corn FBEC5D),
          ['Cornell Red', 'B31B1B'],
          ['Cornflower Blue', '6495ED'],
          %w(Cornsilk FFF8DC),
          ['Cosmic Latte', 'FFF8E7'],
          ['Coyote Brown', '81613E'],
          ['Cotton Candy', 'FFBCD9'],
          %w(Cream FFFDD0),
          %w(Crimson DC143C),
          ['Crimson Glory', 'BE0032'],
          ['Crimson Red', '990000'],
          %w(Cyan 00FFFF),
          ['Cyan Azure', '4E82b4'],
          ['Cyan-Blue Azure', '4682BF'],
          ['Cyan Cobalt Blue', '28589C'],
          ['Cyan Cornflower Blue', '188BC2'],
          ['Cyan (Process)', '00B7EB'],
          ['Cyber Grape', '58427C'],
          ['Cyber Yellow', 'FFD300'],
          %w(Daffodil FFFF31),
          %w(Dandelion F0E130),
          ['Dark Blue', '00008B'],
          ['Dark Blue-Gray', '666699'],
          ['Dark Brown', '654321'],
          ['Dark Brown-Tangelo', '88654E'],
          ['Dark Byzantium', '5D3954'],
          ['Dark Candy Apple Red', 'A40000'],
          ['Dark Cerulean', '08457E'],
          ['Dark Chestnut', '986960'],
          ['Dark Coral', 'CD5B45'],
          ['Dark Cyan', '008B8B'],
          ['Dark Electric Blue', '536878'],
          ['Dark Goldenrod', 'B8860B'],
          ['Dark Gray (X11)', 'A9A9A9'],
          ['Dark Green', '013220'],
          ['Dark Green (X11)', '006400'],
          ['Dark Gunmetal', '006400'],
          ['Dark Imperial Blue', '00416A'],
          ['Dark Imperial Blue', '6E6EF9'],
          ['Dark Jungle Green', '1A2421'],
          ['Dark Khaki', 'BDB76B'],
          ['Dark Lava', '483C32'],
          ['Dark Lavender', '734F96'],
          ['Dark Liver', '534B4F'],
          ['Dark Liver (Horses)', '543D37'],
          ['Dark Magenta', '8B008B'],
          ['Dark Medium Gray', 'A9A9A9'],
          ['Dark Midnight Blue', '003366'],
          ['Dark Moss Green', '4A5D23'],
          ['Dark Olive Green', '556B2F'],
          ['Dark Orange', 'FF8C00'],
          ['Dark Orchid', '9932CC'],
          ['Dark Pastel Blue', '779ECB'],
          ['Dark Pastel Green', '03C03C'],
          ['Dark Pastel Purple', '966FD6'],
          ['Dark Pastel Red', 'C23B22'],
          ['Dark Pink', 'E75480'],
          ['Dark Powder Blue', '003399'],
          ['Dark Puce', '4F3A3C'],
          ['Dark Purple', '301934'],
          ['Dark Raspberry', '872657'],
          ['Dark Red', '8B0000'],
          ['Dark Salmon', 'E9967A'],
          ['Dark Scarlet', '560319'],
          ['Dark Sea Green', '8FBC8F'],
          ['Dark Sienna', '3C1414'],
          ['Dark Sky Blue', '8CBED6'],
          ['Dark Slate Blue', '483D8B'],
          ['Dark Slate Gray', '2F4F4F'],
          ['Dark Spring Green', '177245'],
          ['Dark Tan', '918151'],
          ['Dark Tangerine', 'FFA812'],
          ['Dark Taupe', '483C32'],
          ['Dark Terra Cotta', 'CC4E5C'],
          ['Dark Turquoise', '00CED1'],
          ['Dark Vanilla', 'D1BEA8'],
          ['Dark Violet', '9400D3'],
          ['Dark Yellow', '9B870C'],
          ['Dartmouth Green', '00703C'],
          ["Davy's Grey", '555555'],
          ['Debian Red', 'D70A53'],
          ['Deep Aquamarine', '40826D'],
          ['Deep Carmine', 'A9203E'],
          ['Deep Carmine Pink', 'EF3038'],
          ['Deep Carrot Orange', 'E9692C'],
          ['Deep Cerise', 'DA3287'],
          ['Deep Champagne', 'FAD6A5'],
          ['Deep Chestnut', 'B94E48'],
          ['Deep Coffee', '704241'],
          ['Deep Fuchsia', 'C154C1'],
          ['Deep Green', '056608'],
          ['Deep Green-Cyan Turquoise', '0E7C61'],
          ['Deep Jungle Green', '004B49'],
          ['Deep Koamaru', '333366'],
          ['Deep Lemon', 'F5C71A'],
          ['Deep Lilac', '9955BB'],
          ['Deep Magenta', 'CC00CC'],
          ['Deep Maroon', '820000'],
          ['Deep Mauve', 'D473D4'],
          ['Deep Moss Green', '355E3B'],
          ['Deep Peach', 'FFCBA4'],
          ['Deep Pink', 'FF1493'],
          ['Deep Puce', 'A95C68'],
          ['Deep Red', '850101'],
          ['Deep Ruby', '843F5B'],
          ['Deep Saffron', 'FF9933'],
          ['Deep Sky Blue', '00BFFF'],
          ['Deep Space Sparkle', '4A646C'],
          ['Deep Spring Bud', '556B2F'],
          ['Deep Taupe', '7E5E60'],
          ['Deep Tuscan Red', '66424D'],
          ['Deep Violet', '330066'],
          %w(Deer BA8759),
          %w(Denim 1560BD),
          ['Desaturated Cyan', '669999'],
          %w(Desert C19A6B),
          ['Desert Sand', 'EDC9AF'],
          %w(Desire EA3C53),
          %w(Diamond B9F2FF),
          ['Dim Gray', '696969'],
          %w(Dirt 9B7653),
          ['Dodger Blue', '1E90FF'],
          ['Dogwood Rose', 'D71868'],
          ['Dollar Bill', '85BB65'],
          ['Donkey Brown', '664C28'],
          %w(Drab 967117),
          ['Duke Blue', '00009C'],
          ['Dust Storm', 'E5CCC9'],
          ['Dutch White', 'EFDFBB'],
          ['Earth Yellow', 'E1A95F'],
          %w(Ebony 555D50),
          %w(Ecru C2B280),
          ['Eerie Black', '1B1B1B'],
          %w(Eggplant 614051),
          %w(Eggshell F0EAD6),
          ['Egyptian Blue', '1034A6'],
          ['Electric Blue', '7DF9FF'],
          ['Electric Crimson', 'FF003F'],
          ['Electric Cyan', '00FFFF'],
          ['Electric Green', '00FF00'],
          ['Electric Indigo', '6F00FF'],
          ['Electric Lavender', 'F4BBFF'],
          ['Electric Lime', 'CCFF00'],
          ['Electric Purple', 'BF00FF'],
          ['Electric Ultramarine', '3F00FF'],
          ['Electric Violet', '8F00FF'],
          ['Electric Yellow', 'FFFF33'],
          %w(Emerald 50C878),
          %w(Eminence 6C3082),
          ['English Green', '1B4D3E'],
          ['English Lavender', 'B48395'],
          ['English Red', 'AB4B52'],
          ['English Violet', '563C5C'],
          ['Eton Blue', '96C8A2'],
          %w(Eucalyptus 44D7A8),
          %w(Fallow C19A6B),
          ['Falu Red', '801818'],
          %w(Fandango B53389),
          ['Fandango Pink', 'DE5285'],
          ['Fashion Fuchsia', 'F400A1'],
          %w(Fawn E5AA70),
          %w(Feldgrau 4D5D53),
          %w(Feldspar FDD5B1),
          ['Fern Green', '4F7942'],
          ['Ferrari Red', 'FF2800'],
          ['Field Drab', '6C541E'],
          %w(Firebrick B22222),
          ['Fire Engine Red', 'CE2029'],
          %w(Flame E25822),
          ['Flamingo Pink', 'FC8EAC'],
          %w(Flattery 6B4423),
          %w(Flavescent F7E98E),
          %w(Flax EEDC82),
          %w(Flirt A2006D),
          ['Floral White', 'FFFAF0'],
          ['Fluorescent Orange', 'FFBF00'],
          ['Fluorescent Pink', 'FF1493'],
          ['Fluorescent Yellow', 'CCFF00'],
          %w(Folly FF004F),
          ['Forest Green (Traditional)', '014421'],
          ['Forest Green (Web)', '228B22'],
          ['French Beige', 'A67B5B'],
          ['French Bistre', '856D4D'],
          ['French Blue', '0072BB'],
          ['French Fuchsia', 'FD3F92'],
          ['French Lilac', '86608E'],
          ['French Lime', '9EFD38'],
          ['French Mauve', 'D473D4'],
          ['French Pink', 'FD6C9E'],
          ['French Plum', '811453'],
          ['French Puce', '4E1609'],
          ['French Raspberry', 'C72C48'],
          ['French Rose', 'F64A8A'],
          ['French Sky Blue', '77B5FE'],
          ['French Violet', '8806CE'],
          ['French Wine', 'AC1E44'],
          ['Fresh Air', 'A6E7FF'],
          %w(Fuchsia FF00FF),
          ['Fuchsia (Crayola)', 'C154C1'],
          ['Fuchsia Pink', 'FF77FF'],
          ['Fuchsia Purple', 'CC397B'],
          ['Fuchsia Rose', 'C74375'],
          %w(Fulvous E48400),
          ['Fuzzy Wuzzy', 'CC6666'],
          %w(Gainsboro DCDCDC),
          %w(Gamboge E49B0F),
          ['Gamboge Orange (Brown)', '996600'],
          ['Generic Viridian', '007F66'],
          ['Ghost White', 'F8F8FF'],
          ['Giants Orange', 'FE5A1D'],
          %w(Glaucous 6082B6),
          %w(Glitter E6E8FA),
          ['GO Green', '00AB66'],
          ['Gold (Metallic)', 'D4AF37'],
          ['Gold (Web) (Golden)', 'FFD700'],
          ['Gold Fusion', '85754E'],
          ['Golden Brown', '996515'],
          ['Golden Poppy', 'FCC200'],
          ['Golden Yellow', 'FFDF00'],
          %w(Goldenrod DAA520),
          ['Granny Smith Apple', 'A8E4A0'],
          %w(Grape 6F2DA8),
          %w(Gray 808080),
          ['Gray (HTML/CSS Gray)', '808080'],
          ['Gray (X11 Gray)', 'BEBEBE'],
          ['Gray-Asparagus', '465945'],
          ['Gray-Blue', '8C92AC'],
          ['Green (Color Wheel) (X11 Green)', '00FF00'],
          ['Green (Crayola)', '1CAC78'],
          ['Green (HTML/CSS Color)', '008000'],
          ['Green (Munsell)', '00A877'],
          ['Green (NCS)', '009F6B'],
          ['Green (Pantone)', '00AD43'],
          ['Green (Pigment)', '00A550'],
          ['Green (RYB)', '66B032'],
          ['Green-Blue', '1164B4'],
          ['Green-Cyan', '009966'],
          ['Green-Yellow', 'ADFF2F'],
          %w(Grizzly 885818),
          %w(Grullo A99A86),
          ['Guppie Green', '00FF7F'],
          %w(Grussrel B06500),
          %w(Gunmetal 2a3439),
          ['Halayà Úbe', '663854'],
          ['Han Blue', '446CCF'],
          ['Han Purple', '5218FA'],
          ['Hansa Yellow', 'E9D66B'],
          %w(Harlequin 3FFF00),
          ['Harlequin Green', '46CB18'],
          ['Harvard Crimson', 'C90016'],
          ['Harvest Gold', 'DA9100'],
          ['Heart Gold', '808000'],
          %w(Heliotrope DF73FF),
          ['Heliotrope Gray', 'AA98A9'],
          ['Heliotrope Magenta', 'AA00BB'],
          ['Hollywood Cerise', 'F400A1'],
          %w(Honeydew F0FFF0),
          ['Honolulu Blue', '006DB0'],
          ["Hooker's Green", '49796B'],
          ['Hot Magenta', 'FF1DCE'],
          ['Hot Pink', 'FF69B4'],
          ['Hunter Green', '355E3B'],
          %w(Iceberg 71A6D2),
          %w(Icterine FCF75E),
          ['Illuminating Emerald', '319177'],
          %w(Imperial 602F6B),
          ['Imperial Blue', '002395'],
          ['Imperial Purple', '66023C'],
          ['Imperial Red', 'ED2939'],
          %w(Inchworm B2EC5D),
          %w(Independence 4C516D),
          ['India Green', '138808'],
          ['Indian Red', 'CD5C5C'],
          ['Indian Yellow', 'E3A857'],
          %w(Indigo 4B0082),
          ['Indigo Dye', '091F92'],
          ['Indigo (Web)', '4B0082'],
          ['International Klein Blue', '002FA7'],
          ['International Orange (Aerospace)', 'FF4F00'],
          ['International Orange (Engineering)', 'BA160C'],
          ['International Orange (Golden Gate Bridge)', 'C0362C'],
          %w(Iris 5A4FCF),
          %w(Irresistible B3446C),
          %w(Isabelline F4F0EC),
          ['Islamic Green', '009000'],
          ['Italian Sky Blue', 'B2FFFF'],
          %w(Ivory FFFFF0),
          %w(Jade 00A86B),
          ['Japanese Carmine', '9D2933'],
          ['Japanese Indigo', '264348'],
          ['Japanese Violet', '5B3256'],
          %w(Jasmine F8DE7E),
          %w(Jasper D73B3E),
          ['Jawad/Chicken Color (HTML/CSS) (Khaki)', 'C3B091'],
          ['Jazzberry Jam', 'A50B5E'],
          ['Jelly Bean', 'DA614E'],
          %w(Jet 343434),
          %w(Jonquil F4CA16),
          ['Jordy Blue', '8AB9F1'],
          ['June Bud', 'BDDA57'],
          ['Jungle Green', '29AB87'],
          ['Kelly Green', '4CBB17'],
          ['Kenyan Copper', '7C1C05'],
          %w(Keppel 3AB09E),
          ['Khaki (HTML/CSS) (Khaki)', 'C3B091'],
          ['Khaki (X11) (Light Khaki)', 'F0E68C'],
          %w(Kobe 882D17),
          %w(Kobi E79FC4),
          %w(Kobicha 6B4423),
          ['Kombu Green', '354230'],
          ['KU Crimson', 'E8000D'],
          ['La Salle Green', '087830'],
          ['Languid Lavender', 'D6CADD'],
          ['Lapis Lazuli', '26619C'],
          ['Laser Lemon', 'FFFF66'],
          ['Laurel Green', 'A9BA9D'],
          %w(Lava CF1020),
          ['Lavender (Floral)', 'B57EDC'],
          ['Lavender (Web)', 'E6E6FA'],
          ['Lavender Blue', 'CCCCFF'],
          ['Lavender Blush', 'FFF0F5'],
          ['Lavender Gray', 'C4C3D0'],
          ['Lavender Indigo', '9457EB'],
          ['Lavender Magenta', 'EE82EE'],
          ['Lavender Mist', 'E6E6FA'],
          ['Lavender Pink', 'FBAED2'],
          ['Lavender Purple', '967BB6'],
          ['Lavender Rose', 'FBA0E3'],
          ['Lawn Green', '7CFC00'],
          %w(Lemon FFF700),
          ['Lemon Chiffon', 'FFFACD'],
          ['Lemon Curry', 'CCA01D'],
          ['Lemon Glacier', 'FDFF00'],
          ['Lemon Lime', 'E3FF00'],
          ['Lemon Meringue', 'F6EABE'],
          ['Lemon Yellow', 'FFF44F'],
          %w(Lenurple BA93D8),
          %w(Licorice 1A1110),
          %w(Liberty 545AA7),
          ['Light Apricot', 'FDD5B1'],
          ['Light Blue', 'ADD8E6'],
          ['Light Brilliant Red', 'FE2E2E'],
          ['Light Brown', 'B5651D'],
          ['Light Carmine Pink', 'E66771'],
          ['Light Cobalt Blue', '88ACE0'],
          ['Light Coral', 'F08080'],
          ['Light Cornflower Blue', '93CCEA'],
          ['Light Crimson', 'F56991'],
          ['Light Cyan', 'E0FFFF'],
          ['Light Deep Pink', 'FF5CCD'],
          ['Light French Beige', 'C8AD7F'],
          ['Light Fuchsia Pink', 'F984EF'],
          ['Light Goldenrod Yellow', 'FAFAD2'],
          ['Light Gray', 'D3D3D3'],
          ['Light Grayish Magenta', 'CC99CC'],
          ['Light Green', '90EE90'],
          ['Light Hot Pink', 'FFB3DE'],
          ['Light Khaki', 'F0E68C'],
          ['Light Medium Orchid', 'D39BCB'],
          ['Light Moss Green', 'ADDFAD'],
          ['Light Orange', 'FFE0C0'],
          ['Light Orchid', 'E6A8D7'],
          ['Light Pastel Purple', 'B19CD9'],
          ['Light Pink', 'FFB6C1'],
          ['Light Red Ochre', 'E97451'],
          ['Light Salmon', 'FFA07A'],
          ['Light Salmon Pink', 'FF9999'],
          ['Light Sea Green', '20B2AA'],
          ['Light Sky Blue', '87CEFA'],
          ['Light Slate Gray', '778899'],
          ['Light Steel Blue', 'B0C4DE'],
          ['Light Taupe', 'B38B6D'],
          ['Light Thulian Pink', 'E68FAC'],
          ['Light Yellow', 'FFFFE0'],
          %w(Lilac C8A2C8),
          ['Lime (Color Wheel)', 'BFFF00'],
          ['Lime (Web) (X11 Green)', '00FF00'],
          ['Lime Green', '32CD32'],
          %w(Limerick 9DC209),
          ['Lincoln Green', '195905'],
          %w(Linen FAF0E6),
          %w(Lion C19A6B),
          ['Liseran Purple', 'DE6FA1'],
          ['Little Boy Blue', '6CA0DC'],
          %w(Liver 674C47),
          ['Liver (Dogs)', 'B86D29'],
          ['Liver (Organ)', '6C2E1F'],
          ['Liver Chestnut', '987456'],
          %w(Livid 6699CC),
          %w(Lumber FFE4CD),
          %w(Lust E62020),
          ['Macaroni And Cheese', 'FFBD88'],
          %w(Magenta FF00FF),
          ['Magenta (Crayola)', 'FF55A3'],
          ['Magenta (Dye)', 'CA1F7B'],
          ['Magenta (Pantone)', 'D0417E'],
          ['Magenta (Process)', 'FF0090'],
          ['Magenta Haze', '9F4576'],
          ['Magenta-Pink', 'CC338B'],
          ['Magic Mint', 'AAF0D1'],
          %w(Magnolia F8F4FF),
          %w(Mahogany C04000),
          %w(Maize FBEC5D),
          ['Majorelle Blue', '6050DC'],
          %w(Malachite 0BDA51),
          %w(Manatee 979AAA),
          ['Mango Tango', 'FF8243'],
          %w(Mantis 74C365),
          ['Mardi Gras', '880085'],
          %w(Marigold EAA221),
          ['Maroon (Crayola)', 'C32148'],
          ['Maroon (HTML/CSS)', '800000'],
          ['Maroon (X11)', 'B03060'],
          %w(Mauve E0B0FF),
          ['Mauve Taupe', '915F6D'],
          %w(Mauvelous EF98AA),
          ['May Green', '4C9141'],
          ['Maya Blue', '73C2FB'],
          ['Meat Brown', 'E5B73B'],
          ['Medium Aquamarine', '66DDAA'],
          ['Medium Blue', '0000CD'],
          ['Medium Candy Apple Red', 'E2062C'],
          ['Medium Carmine', 'AF4035'],
          ['Medium Champagne', 'F3E5AB'],
          ['Medium Electric Blue', '035096'],
          ['Medium Jungle Green', '1C352D'],
          ['Medium Lavender Magenta', 'DDA0DD'],
          ['Medium Orchid', 'BA55D3'],
          ['Medium Persian Blue', '0067A5'],
          ['Medium Purple', '9370DB'],
          ['Medium Red-violet', 'BB3385'],
          ['Medium Ruby', 'AA4069'],
          ['Medium Sea Green', '3CB371'],
          ['Medium Sky Blue', '80DAEB'],
          ['Medium Slate Blue', '7B68EE'],
          ['Medium Spring Bud', 'C9DC87'],
          ['Medium Spring Green', '00FA9A'],
          ['Medium Taupe', '674C47'],
          ['Medium Turquoise', '48D1CC'],
          ['Medium Tuscan Red', '79443B'],
          ['Medium Vermilion', 'D9603B'],
          ['Medium Violet-Red', 'C71585'],
          ['Mellow Apricot', 'F8B878'],
          ['Mellow Yellow', 'F8DE7E'],
          %w(Melon FDBCB4),
          ['Metallic Seaweed', '0A7E8C'],
          ['Metallic Sunburst', '9C7C38'],
          ['Mexican Pink', 'E4007C'],
          ['Midnight Blue', '191970'],
          ['Midnight Green (Eagle Green)', '004953'],
          ['Mikado Yellow', 'FFC40C'],
          %w(Mindaro E3F988),
          %w(Ming 36747D),
          %w(Mint 3EB489),
          ['Mint Cream', 'F5FFFA'],
          ['Mint Green', '98FF98'],
          ['Misty Rose', 'FFE4E1'],
          %w(Moccasin FAEBD7),
          ['Mode Beige', '967117'],
          ['Moonstone Blue', '73A9C2'],
          ['Mordant Red 19', 'AE0C00'],
          ['Moss Green', '8A9A5B'],
          ['Mountain Meadow', '30BA8F'],
          ['Mountbatten Pink', '997A8D'],
          ['MSU Green', '18453B'],
          ['Mughal Green', '306030'],
          %w(Mulberry C54B8C),
          %w(Mustard FFDB58),
          ['Myrtle Green', '317873'],
          ['Nadeshiko Pink', 'F6ADC6'],
          ['Napier Green', '2A8000'],
          ['Naples Yellow', 'FADA5E'],
          ['Navajo White', 'FFDEAD'],
          %w(Navy 000080),
          ['Navy Purple', '9457EB'],
          ['Neon Carrot', 'FFA343'],
          ['Neon Fuchsia', 'FE4164'],
          ['Neon Green', '39FF14'],
          ['New Car', '214FC6'],
          ['New York Pink', 'D7837F'],
          ['Non-Photo Blue', 'A4DDED'],
          ['North Texas Green', '059033'],
          %w(Nyanza E9FFDB),
          ['Ocean Boat Blue', '0077BE'],
          %w(Ochre CC7722),
          ['Office Green', '008000'],
          ['Old Burgundy', '43302E'],
          ['Old Gold', 'CFB53B'],
          ['Old Heliotrope', '563C5C'],
          ['Old Lace', 'FDF5E6'],
          ['Old Lavender', '796878'],
          ['Old Mauve', '673147'],
          ['Old Moss Green', '867E36'],
          ['Old Rose', 'C08081'],
          ['Old Silver', '848482'],
          %w(Olive 808000),
          ['Olive Drab (3)', '6B8E23'],
          ['Olive Drab 7', '3C341F'],
          %w(Olivine 9AB973),
          %w(Onyx 353839),
          ['Opera Mauve', 'B784A7'],
          ['Orange (Color Wheel)', 'FF7F00'],
          ['Orange (Crayola)', 'FF7538'],
          ['Orange (Pantone)', 'FF5800'],
          ['Orange (RYB)', 'FB9902'],
          ['Orange (Web)', 'FFA500'],
          ['Orange Peel', 'FF9F00'],
          ['Orange-Red', 'FF4500'],
          ['Orange-Yellow', 'F8D568'],
          %w(Orchid DA70D6),
          ['Orchid Pink', 'F2BDCD'],
          ['Orioles Orange', 'FB4F14'],
          ['Otter Brown', '654321'],
          ['Outer Space', '414A4C'],
          ['Outrageous Orange', 'FF6E4A'],
          ['Oxford Blue', '002147'],
          ['OU Crimson Red', '990000'],
          ['Pacific Blue', '1CA9C9'],
          ['Pakistan Green', '006600'],
          ['Palatinate Blue', '273BE2'],
          ['Palatinate Purple', '682860'],
          ['Pale Aqua', 'BCD4E6'],
          ['Pale Blue', 'AFEEEE'],
          ['Pale Brown', '987654'],
          ['Pale Carmine', 'AF4035'],
          ['Pale Cerulean', '9BC4E2'],
          ['Pale Chestnut', 'DDADAF'],
          ['Pale Copper', 'DA8A67'],
          ['Pale Cornflower Blue', 'ABCDEF'],
          ['Pale Cyan', '87D3F8'],
          ['Pale Gold', 'E6BE8A'],
          ['Pale Goldenrod', 'EEE8AA'],
          ['Pale Green', '98FB98'],
          ['Pale Lavender', 'DCD0FF'],
          ['Pale Magenta', 'F984E5'],
          ['Pale Magenta-Pink', 'FF99CC'],
          ['Pale Pink', 'FADADD'],
          ['Pale Plum', 'DDA0DD'],
          ['Pale Red-Violet', 'DB7093'],
          ['Pale Robin Egg Blue', '96DED1'],
          ['Pale Silver', 'C9C0BB'],
          ['Pale Spring Bud', 'ECEBBD'],
          ['Pale Taupe', 'BC987E'],
          ['Pale Turquoise', 'AFEEEE'],
          ['Pale Violet', 'CC99FF'],
          ['Pale Violet-Red', 'DB7093'],
          ['Pansy Purple', '78184A'],
          ['Paolo Veronese Green', '009B7D'],
          ['Papaya Whip', 'FFEFD5'],
          ['Paradise Pink', 'E63E62'],
          ['Paris Green', '50C878'],
          ['Pastel Blue', 'AEC6CF'],
          ['Pastel Brown', '836953'],
          ['Pastel Gray', 'CFCFC4'],
          ['Pastel Green', '77DD77'],
          ['Pastel Magenta', 'F49AC2'],
          ['Pastel Orange', 'FFB347'],
          ['Pastel Pink', 'DEA5A4'],
          ['Pastel Purple', 'B39EB5'],
          ['Pastel Red', 'FF6961'],
          ['Pastel Violet', 'CB99C9'],
          ['Pastel Yellow', 'FDFD96'],
          %w(Patriarch 800080),
          ["Payne's Grey", '536878'],
          %w(Peach FFE5B4),
          %w(Peach FFCBA4),
          ['Peach-Orange', 'FFCC99'],
          ['Peach Puff', 'FFDAB9'],
          ['Peach-Yellow', 'FADFAD'],
          %w(Pear D1E231),
          %w(Pearl EAE0C8),
          ['Pearl Aqua', '88D8C0'],
          ['Pearly Purple', 'B768A2'],
          %w(Peridot E6E200),
          %w(Periwinkle CCCCFF),
          ['Persian Blue', '1C39BB'],
          ['Persian Green', '00A693'],
          ['Persian Indigo', '32127A'],
          ['Persian Orange', 'D99058'],
          ['Persian Pink', 'F77FBE'],
          ['Persian Plum', '701C1C'],
          ['Persian Red', 'CC3333'],
          ['Persian Rose', 'FE28A2'],
          %w(Persimmon EC5800),
          %w(Peru CD853F),
          %w(Phlox DF00FF),
          ['Phthalo Blue', '000F89'],
          ['Phthalo Green', '123524'],
          ['Picton Blue', '45B1E8'],
          ['Pictorial Carmine', 'C30B4E'],
          ['Piggy Pink', 'FDDDE6'],
          ['Pine Green', '01796F'],
          %w(Pineapple 563C5C),
          %w(Pink FFC0CB),
          ['Pink (Pantone)', 'D74894'],
          ['Pink Flamingo', 'FC74FD'],
          ['Pink Lace', 'FFDDF4'],
          ['Pink Lavender', 'D8B2D1'],
          ['Pink-Orange', 'FF9966'],
          ['Pink Pearl', 'E7ACCF'],
          ['Pink Raspberry', '980036'],
          ['Pink Sherbet', 'F78FA7'],
          %w(Pistachio 93C572),
          %w(Platinum E5E4E2),
          %w(Plum 8E4585),
          ['Plum (Web)', 'DDA0DD'],
          ['Pomp And Power', '86608E'],
          %w(Popstar BE4F62),
          ['Portland Orange', 'FF5A36'],
          ['Powder Blue', 'B0E0E6'],
          ['Princeton Orange', 'F58025'],
          %w(Prune 701C1C),
          ['Prussian Blue', '003153'],
          ['Psychedelic Purple', 'DF00FF'],
          %w(Puce CC8899),
          ['Puce Red', '722F37'],
          ['Pullman Brown (UPS Brown)', '644117'],
          ['Pullman Green', '3B331C'],
          %w(Pumpkin FF7518),
          ['Purple (HTML)', '800080'],
          ['Purple (Munsell)', '9F00C5'],
          ['Purple (X11)', 'A020F0'],
          ['Purple Heart', '69359C'],
          ['Purple Mountain Majesty', '9678B6'],
          ['Purple Navy', '4E5180'],
          ['Purple Pizzazz', 'FE4EDA'],
          ['Purple Taupe', '50404D'],
          %w(Purpureus 9A4EAE),
          %w(Quartz 51484F),
          ['Queen Blue', '436B95'],
          ['Queen Pink', 'E8CCD7'],
          ['Quinacridone Magenta', '8E3A59'],
          %w(Rackley 5D8AA8),
          ['Radical Red', 'FF355E'],
          %w(Rajah FBAB60),
          %w(Raspberry E30B5D),
          ['Raspberry Glace', '915F6D'],
          ['Raspberry Pink', 'E25098'],
          ['Raspberry Rose', 'B3446C'],
          ['Raw Sienna', 'D68A59'],
          ['Raw Umber', '826644'],
          ['Razzle Dazzle Rose', 'FF33CC'],
          %w(Razzmatazz E3256B),
          ['Razzmic Berry', '8D4E85'],
          ['Rebecca Purple', '663399'],
          %w(Red FF0000),
          ['Red (Crayola)', 'EE204D'],
          ['Red (Munsell)', 'F2003C'],
          ['Red (NCS)', 'C40233'],
          ['Red (Pantone)', 'ED2939'],
          ['Red (Pigment)', 'ED1C24'],
          ['Red (RYB)', 'FE2712'],
          ['Red-Brown', 'A52A2A'],
          ['Red Devil', '860111'],
          ['Red-Orange', 'FF5349'],
          ['Red-Purple', 'E40078'],
          ['Red-Violet', 'C71585'],
          %w(Redwood A45A52),
          %w(Regalia 522D80),
          ['Registration Black', '000000'],
          ['Resolution Blue', '002387'],
          %w(Rhythm 777696),
          ['Rich Black', '004040'],
          ['Rich Black (Typical)', '000000'],
          ['Rich Black (FOGRA29)', '010B13'],
          ['Rich Black (FOGRA39)', '010203'],
          ['Rich Brilliant Lavender', 'F1A7FE'],
          ['Rich Carmine', 'D70040'],
          ['Rich Electric Blue', '0892D0'],
          ['Rich Lavender', 'A76BCF'],
          ['Rich Lilac', 'B666D2'],
          ['Rich Maroon', 'B03060'],
          ['Rifle Green', '444C38'],
          ['Roast Coffee', '704241'],
          ['Robin Egg Blue', '00CCCC'],
          ['Rocket Metallic', '8A7F80'],
          ['Roman Silver', '838996'],
          %w(Rose FF007F),
          ['Rose Bonbon', 'F9429E'],
          ['Rose Ebony', '674846'],
          ['Rose Gold', 'B76E79'],
          ['Rose Madder', 'E32636'],
          ['Rose Pink', 'FF66CC'],
          ['Rose Quartz', 'AA98A9'],
          ['Rose Red', 'C21E56'],
          ['Rose Taupe', '905D5D'],
          ['Rose Vale', 'AB4E52'],
          %w(Rosewood 65000B),
          ['Rosso Corsa', 'D40000'],
          ['Rosy Brown', 'BC8F8F'],
          ['Royal Azure', '0038A8'],
          ['Royal Blue', '002366'],
          ['Royal Blue', '4169E1'],
          ['Royal Fuchsia', 'CA2C92'],
          ['Royal Purple', '7851A9'],
          ['Royal Yellow', 'FADA5E'],
          %w(Ruber CE4676),
          ['Rubine Red', 'D10056'],
          %w(Ruby E0115F),
          ['Ruby Red', '9B111E'],
          %w(Ruddy FF0028),
          ['Ruddy Brown', 'BB6528'],
          ['Ruddy Pink', 'E18E96'],
          %w(Rufous A81C07),
          %w(Russet 80461B),
          ['Russian Green', '679267'],
          ['Russian Violet', '32174D'],
          %w(Rust B7410E),
          ['Rusty Red', 'DA2C43'],
          ['Sacramento State Green', '00563F'],
          ['Saddle Brown', '8B4513'],
          ['Safety Orange', 'FF7800'],
          ['Safety Orange (Blaze Orange)', 'FF6700'],
          ['Safety Yellow', 'EED202'],
          %w(Saffron F4C430),
          %w(Sage BCB88A),
          ["St. Patrick's Blue", '23297A'],
          %w(Salmon FA8072),
          ['Salmon Pink', 'FF91A4'],
          %w(Sand C2B280),
          ['Sand Dune', '967117'],
          %w(Sandstorm ECD540),
          ['Sandy Brown', 'F4A460'],
          ['Sandy Taupe', '967117'],
          %w(Sangria 92000A),
          ['Sap Green', '507D2A'],
          %w(Sapphire 0F52BA),
          ['Sapphire Blue', '0067A5'],
          ['Satin Sheen Gold', 'CBA135'],
          %w(Scarlet FF2400),
          %w(Scarlet FD0E35),
          ['Schauss Pink', 'FF91AF'],
          ['School Bus Yellow', 'FFD800'],
          ["Screamin' Green", '76FF7A'],
          ['Sea Blue', '006994'],
          ['Sea Green', '2E8B57'],
          ['Seal Brown', '59260B'],
          %w(Seashell FFF5EE),
          ['Selective Yellow', 'FFBA00'],
          %w(Sepia 704214),
          %w(Shadow 8A795D),
          ['Shadow Blue', '778BA5'],
          %w(Shampoo FFCFF1),
          ['Shamrock Green', '009E60'],
          ['Sheen Green', '8FD400'],
          ['Shimmering Blush', 'D98695'],
          ['Shocking Pink', 'FC0FC0'],
          ['Shocking Pink (Crayola)', 'FF6FFF'],
          %w(Sienna 882D17),
          %w(Silver C0C0C0),
          ['Silver Chalice', 'ACACAC'],
          ['Silver Lake Blue', '5D89BA'],
          ['Silver Pink', 'C4AEAD'],
          ['Silver Sand', 'BFC1C2'],
          %w(Sinopia CB410B),
          %w(Skobeloff 007474),
          ['Sky Blue', '87CEEB'],
          ['Sky Magenta', 'CF71AF'],
          ['Slate Blue', '6A5ACD'],
          ['Slate Gray', '708090'],
          ['Smalt (Dark Powder Blue)', '003399'],
          %w(Smitten C84186),
          %w(Smoke 738276),
          ['Smoky Black', '100C08'],
          ['Smoky Topaz', '933D41'],
          %w(Snow FFFAFA),
          %w(Soap CEC8EF),
          ['Solid Pink', '893843'],
          ['Sonic Silver', '757575'],
          ['Spartan Crimson', '9E1316'],
          ['Space Cadet', '1D2951'],
          ['Spanish Bistre', '807532'],
          ['Spanish Blue', '0070B8'],
          ['Spanish Carmine', 'D10047'],
          ['Spanish Crimson', 'E51A4C'],
          ['Spanish Gray', '989898'],
          ['Spanish Green', '009150'],
          ['Spanish Orange', 'E86100'],
          ['Spanish Pink', 'F7BFBE'],
          ['Spanish Red', 'E60026'],
          ['Spanish Sky Blue', '00FFFF'],
          ['Spanish Violet', '4C2882'],
          ['Spanish Viridian', '007F5C'],
          ['Spicy Mix', '8B5f4D'],
          ['Spiro Disco Ball', '0FC0FC'],
          ['Spring Bud', 'A7FC00'],
          ['Spring Green', '00FF7F'],
          ['Star Command Blue', '007BB8'],
          ['Steel Blue', '4682B4'],
          ['Steel Pink', 'CC33CC'],
          ['Stil De Grain Yellow', 'FADA5E'],
          %w(Stizza 990000),
          %w(Stormcloud 4F666A),
          %w(Straw E4D96F),
          %w(Strawberry FC5A8D),
          %w(Sunglow FFCC33),
          %w(Sunray E3AB57),
          %w(Sunset FAD6A5),
          ['Sunset Orange', 'FD5E53'],
          ['Super Pink', 'CF6BA9'],
          %w(Tan D2B48C),
          %w(Tangelo F94D00),
          %w(Tangerine F28500),
          ['Tangerine Yellow', 'FFCC00'],
          ['Tango Pink', 'E4717A'],
          %w(Taupe 483C32),
          ['Taupe Gray', '8B8589'],
          ['Tea Green', 'D0F0C0'],
          ['Tea Rose (Orange)', 'F88379'],
          ['Tea Rose (Rose)', 'F4C2C2'],
          %w(Teal 008080),
          ['Teal Blue', '367588'],
          ['Teal Deer', '99E6B3'],
          ['Teal Green', '00827F'],
          %w(Telemagenta CF3476),
          %w(Tenné CD5700),
          ['Terra Cotta', 'E2725B'],
          %w(Thistle D8BFD8),
          ['Thulian Pink', 'DE6FA1'],
          ['Tickle Me Pink', 'FC89AC'],
          ['Tiffany Blue', '0ABAB5'],
          ["Tiger's Eye", 'E08D3C'],
          %w(Timberwolf DBD7D2),
          ['Titanium Yellow', 'EEE600'],
          %w(Tomato FF6347),
          %w(Toolbox 746CC0),
          %w(Topaz FFC87C),
          ['Tractor Red', 'FD0E35'],
          ['Trolley Grey', '808080'],
          ['Tropical Rain Forest', '00755E'],
          ['True Blue', '0073CF'],
          ['Tufts Blue', '417DC1'],
          %w(Tulip FF878D),
          %w(Tumbleweed DEAA88),
          ['Turkish Rose', 'B57281'],
          %w(Turquoise 40E0D0),
          ['Turquoise Blue', '00FFEF'],
          ['Turquoise Green', 'A0D6B4'],
          %w(Tuscan FAD6A5),
          ['Tuscan Brown', '6F4E37'],
          ['Tuscan Red', '7C4848'],
          ['Tuscan Tan', 'A67B5B'],
          %w(Tuscany C09999),
          ['Twilight Lavender', '8A496B'],
          ['Tyrian Purple', '66023C'],
          ['UA Blue', '0033AA'],
          ['UA Red', 'D9004C'],
          %w(Ube 8878C3),
          ['UCLA Blue', '536895'],
          ['UCLA Gold', 'FFB300'],
          ['UFO Green', '3CD070'],
          %w(Ultramarine 3F00FF),
          ['Ultramarine Blue', '4166F5'],
          ['Ultra Pink', 'FF6FFF'],
          ['Ultra Red', 'FC6C85'],
          %w(Umber 635147),
          ['Unbleached Silk', 'FFDDCA'],
          ['United Nations Blue', '5B92E5'],
          ['University Of California Gold', 'B78727'],
          ['Unmellow Yellow', 'FFFF66'],
          ['UP Forest Green', '014421'],
          ['UP Maroon', '7B1113'],
          ['Upsdell Red', 'AE2029'],
          %w(Urobilin E1AD21),
          ['USAFA Blue', '004F98'],
          ['USC Cardinal', '990000'],
          ['USC Gold', 'FFCC00'],
          ['University Of Tennessee Orange', 'F77F00'],
          ['Utah Crimson', 'D3003F'],
          %w(Vanilla F3E5AB),
          ['Vanilla Ice', 'F38FA9'],
          ['Vegas Gold', 'C5B358'],
          ['Venetian Red', 'C80815'],
          %w(Verdigris 43B3AE),
          %w(Vermilion E34234),
          %w(Vermilion D9381E),
          %w(Veronica A020F0),
          ['Very Light Azure', '74BBFB'],
          ['Very Light Blue', '6666FF'],
          ['Very Light Malachite Green', '64E986'],
          ['Very Light Tangelo', 'FFB077'],
          ['Very Pale Orange', 'FFDFBF'],
          ['Very Pale Yellow', 'FFFFBF'],
          %w(Violet 8F00FF),
          ['Violet (Color Wheel)', '7F00FF'],
          ['Violet (RYB)', '8601AF'],
          ['Violet (Web)', 'EE82EE'],
          ['Violet-Blue', '324AB2'],
          ['Violet-Red', 'F75394'],
          %w(Viridian 40826D),
          ['Viridian Green', '009698'],
          ['Vista Blue', '7C9ED9'],
          ['Vivid Amber', 'CC9900'],
          ['Vivid Auburn', '922724'],
          ['Vivid Burgundy', '9F1D35'],
          ['Vivid Cerise', 'DA1D81'],
          ['Vivid Cerulean', '00AAEE'],
          ['Vivid Crimson', 'CC0033'],
          ['Vivid Gamboge', 'FF9900'],
          ['Vivid Lime Green', 'A6D608'],
          ['Vivid Malachite', '00CC33'],
          ['Vivid Mulberry', 'B80CE3'],
          ['Vivid Orange', 'FF5F00'],
          ['Vivid Orange Peel', 'FFA000'],
          ['Vivid Orchid', 'CC00FF'],
          ['Vivid Raspberry', 'FF006C'],
          ['Vivid Red', 'F70D1A'],
          ['Vivid Red-tangelo', 'DF6124'],
          ['Vivid Sky Blue', '00CCFF'],
          ['Vivid Tangelo', 'F07427'],
          ['Vivid Tangerine', 'FFA089'],
          ['Vivid Vermilion', 'e56024'],
          ['Vivid Violet', '9F00FF'],
          ['Vivid Yellow', 'FFE302'],
          %w(Volt CEFF00),
          ['Warm Black', '004242'],
          %w(Waterspout A4F4F9),
          %w(Wenge 645452),
          %w(Wheat F5DEB3),
          %w(White FFFFFF),
          ['White Smoke', 'F5F5F5'],
          ['Wild Blue Yonder', 'A2ADD0'],
          ['Wild Orchid', 'D470A2'],
          ['Wild Strawberry', 'FF43A4'],
          ['Wild Watermelon', 'FC6C85'],
          ['Willpower Orange', 'FD5800'],
          ['Windsor Tan', 'A75502'],
          %w(Wine 722F37),
          ['Wine Dregs', '673147'],
          %w(Wisteria C9A0DC),
          ['Wood Brown', 'C19A6B'],
          %w(Xanadu 738678),
          ['Yale Blue', '0F4D92'],
          ['Yankees Blue', '1C2841'],
          %w(Yellow FFFF00),
          ['Yellow (Crayola)', 'FCE883'],
          ['Yellow (Munsell)', 'EFCC00'],
          ['Yellow (NCS)', 'FFD300'],
          ['Yellow (Pantone)', 'FEDF00'],
          ['Yellow (Process)', 'FFEF00'],
          ['Yellow (RYB)', 'FEFE33'],
          ['Yellow-Green', '9ACD32'],
          ['Yellow Orange', 'FFAE42'],
          ['Yellow Rose', 'FFF000'],
          %w(Zaffre 0014A8),
          ['Zinnwaldite Brown', '2C1608'],
          %w(Zomp 39A78E),
          ['Actinic'],
          ['Amarklor'],
          ['Kalish'],
          ['Garrow'],
          ['Infra-White'],
          ['Fuligin'],
          ['Grue'],
          ['Bleen'],
          ['Mull'],
          ['Glow'],
          ['Hooloovoo'],
          ['Ultra Violent'],
          ['Infra Dead'],
          ['Liver Purple'],
          ['Loathsome Lilac'],
          ['Matter Yellow'],
          ['Burnt Hombre'],
          ['Gan Green'],
          ['Octarine'],
          ['Squant'],
          ['Jale'],
          ['Ulfire'],
          ['Dolm'],
          ['The Colour Out Of Space'],
          ['Tang'],
          ['Burn'],
          ['Berl'],
          ['Crynor'],
          ['Nusp'],
          ['Onsible'],
          ['Htun'],
          ['Sangoire'],
          ['Celestewhite'],
          ['The Eighth Ray'],
          ['The Ninth Ray'],
          ['Smaudre'],
          ['Rawn'],
          ['Pallow'],
          ['Plaid'],
          ['Shattan'],
          ['Flange'],
          ['Silentropae']]
    end

    def today
        time = Time.new
        srand time.yday
        chosenColor = colorsCollection[rand(colorsCollection.length)]
        linkColor = ''

        if !chosenColor[1].nil?
            linkColor = "<http://www.colorhexa.com/#{chosenColor[1].downcase}|#{chosenColor[0]}>"
        else
            linkColor = "<http://en.wikipedia.org/wiki/List_of_fictional_colors|#{chosenColor[0]}>"
        end

        "Today's color is #{linkColor}."
    end

    def aura
        time = Time.new
        userSeed = 0

        @username.each_char.with_index do |k, index|
            userSeed += k[0].ord * index * ((time.month - 4).modulo(12) + 1)
        end

        srand userSeed
        chosenColor = colorsCollection[rand(colorsCollection.length)]
        linkColor = ''

        if !chosenColor[1].nil?
            linkColor = "<http://www.colorhexa.com/#{chosenColor[1].downcase}|#{chosenColor[0]}>"
        else
           linkColor = "<http://en.wikipedia.org/wiki/List_of_fictional_colors|#{chosenColor[0]}>"
        end

        "<@#{@username}>, the color of your aura is #{linkColor}."
    end

    def random
        srand
        chosenColor = colorsCollection[rand(colorsCollection.length)]
        linkColor = ''

        if !chosenColor[1].nil?
            linkColor = "<http://www.colorhexa.com/#{chosenColor[1].downcase}|#{chosenColor[0]}>"
        else
           linkColor = "<http://en.wikipedia.org/wiki/List_of_fictional_colors|#{chosenColor[0]}>"
        end

        "Here, take this random color: #{linkColor}."
    end

    def date
        time = Time.new
        colorsCollectionInstance = colorsCollection
        seeds = [time.day * time.year * 32, time.month * time.year, time.year * time.year]
        links = ['', '', '']

        for i in 0..2
            srand seeds[i]
            chosenColor = colorsCollectionInstance[rand(colorsCollectionInstance.length)]

            if !color[1].nil?
                links[i] = "<http://www.colorhexa.com/#{chosenColor[1].downcase}|#{chosenColor[0]}>"
            else
                links[i] = "<http://en.wikipedia.org/wiki/List_of_fictional_colors|#{chosenColor[0]}>"
            end
        end

        "We are the #{links[0]} day of the #{links[1]} month of the #{links[2]} year."
    end

    def hex
        targetColor = @message.sub('color hex', '').strip.upcase

        colorsCollection.each do |color|
            if color[0].downcase != targetColor.downcase then next end

            if !color[1].nil?
                return "You are looking for the <http://www.colorhexa.com/#{color[1].downcase}|#{color[1]}> color."
            else
                return 'This color is <http://en.wikipedia.org/wiki/List_of_fictional_colors|fictional>.'
            end
        end

        "I don't know this color"
    end

    def name
        targetColor = @message.split(' ').last.upcase

        colorsCollection.each do |color|
            if color[1].nil? || color[1] != targetColor then next end

            return "You are looking for the <http://www.colorhexa.com/#{color[1].downcase}|#{color[0]}> color."
        end

        "I don't know this color."
    end
end
